
spring.application.name=bookManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/bookDB
spring.datasource.username=postgres
spring.datasource.password=khizardatabase

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
