spring.application.name=ProfileDemo
app.welcome.message =LOCAL: Hello , Wellcome to my application .
app.welcome.code = 200

app.welcome.users = Khizar,Taha,Hassan,Aftab

#spring.profiles.active = dev

