spring.application.name=DemoJdbc

spring.datasource.url=jdbc:postgresql://localhost:5432/DemoJdbc
spring.datasource.username=postgres
spring.datasource.password=khizardatabase
spring.datasource.driver-class-name=org.postgresql.Driver